services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./ai/db/init:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.7.1-python3.11
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_USERNAME}
      - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./ai/airflow/requirements.txt:/opt/airflow/requirements.txt
    command: >
      bash -c "airflow db init && airflow users create --username ${AIRFLOW_USERNAME} --password ${AIRFLOW_PASSWORD} --firstname admin --lastname admin --role Admin --email admin@example.com"
  airflow:
    image: apache/airflow:2.7.1-python3.11
    container_name: airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - VECTOR_DB_NAME=${VECTOR_DB_NAME}
      - OPENAI_API_KEY=${GMS_API_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - GMS_API_KEY=${GMS_API_KEY}
      - PYTHONPATH=/opt/airflow/dags:/opt/airflow/lib
    volumes:
      - ./ai/airflow/dags:/opt/airflow/dags
      - ./ai/airflow/lib:/opt/airflow/lib
      - ./ai/airflow/requirements.txt:/opt/airflow/requirements.txt
    ports:
      - "9000:8080"
    command: bash -c "python -m pip install --no-cache-dir -r /opt/airflow/requirements.txt && airflow scheduler & airflow webserver"

  ai-server:
    build:
      context: .
      dockerfile: ai/Dockerfile
    container_name: ai_server
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      # 코드 변경 시 컨테이너 내부의 /app 디렉토리에 자동 반영
      - .:/app # 배포 시 삭제 !!!!!
    restart: always
    command: uvicorn ai.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - default
      - proxy_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: akkubangkku_zookeeper
    # ports:
    #   - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/zookeeper/data:/var/lib/zookeeper/data
      - ./data/zookeeper/log:/var/lib/zookeeper/log

  # Kafka 메시지 브로커
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: akkubangkku_kafka
    ports:
      - "28080:28080"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # 내부 도커 통신용: akkubangkku_kafka:29092
      # 로컬 호스트 접속용: localhost:28080
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:28080
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:28080
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 29092 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: akkubangkku_kafka_ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: Akkubangkku-Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka

  # Kafka 토픽 자동 생성 init 컨테이너
  kafka-init:
    build:
      context: ./data/kafka-init
    container_name: akkubangkku_kafka_init
    depends_on:
      kafka:
        condition: service_healthy
    restart: "no"
  # 백엔드 컨테이너
  backend:
    build:
      context: ./app/backend # 백엔드 코드가 있는 경로
      dockerfile: Dockerfile
    container_name: akku_backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy # DB가 완전히 뜬 후에 백엔드 실행
      kafka:
        condition: service_healthy # Kafka가 완전히 뜬 후에 백엔드 실행
    env_file:
      - .env # 최상단 .env 파일의 변수들(JWT, KAKAO 등)을 주입받음
    environment:
      # application.yml의 기본값을 도커 내부 통신용으로 덮어쓰기
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EXTERNAL_FASTAPI_BASE_URL=http://ai-server:8000 # localhost:8000 대신 ai_server 컨테이너 이름 사용
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - OFFLINE_PAYMENT_SYSTEM_KEY=${OFFLINE_PAYMENT_SYSTEM_KEY}
    restart: always
    networks:
      - default
      - proxy_net

  # frontend:
  #   build:
  #     context: ./app/frontend
  #     dockerfile: Dockerfile
  #   container_name: akku_frontend
  #   command: npm start
  #   depends_on:
  #     backend:
  #       condition: service_started
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./app/frontend:/app # 코드 변경 시 컨테이너 내부의 /app 디렉토리에 자동 반영
  #     - /app/node_modules # node_modules는 호스트와 공유하지 않음 (컨테이너 내부에서 설치)
  #   env_file:
  #     - .env # 최상단 .env 파일의 변수들(JWT, KAKAO 등)을 주입받음
  #   restart: always

  # Spark Master: 클러스터 매니저 역할
  spark-master:
    image: apache/spark:3.5.1-python3
    container_name: akkubangkku_spark_master
    user: root
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - SPARK_MODE=master
    ports:
      - "18080:8080"
      - "7077:7077" # spark 7077은 내부용이면 제거 검토
    volumes:
      - ./data/spark:/opt/spark/work-dir
    command: >
      /bin/bash -c " pip install --no-cache-dir redis psycopg2-binary && /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master &  echo 'Waiting for Master to start...'; sleep 20; /opt/spark/bin/spark-submit  --master spark://spark-master:7077  --conf spark.sql.streaming.checkpointLocation=/opt/spark/work-dir/checkpoints/realtime-report --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1  /opt/spark/work-dir/realtime_report.py"

  spark-worker:
    image: apache/spark:3.5.1-python3
    container_name: akkubangkku_spark_worker
    user: root
    env_file:
      - .env
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    volumes:
      - ./data/spark:/opt/spark/work-dir
    command: >
      /bin/bash -c "pip install redis psycopg2-binary &&  /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  # Redis: 실시간 리포트용 Hot-Data 저장소
  redis:
    image: redis:latest
    container_name: akkubangkku_redis
    command: redis-server --appendonly yes # [중요] AOF 기능 활성화
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      # 명령 받을 준비 되었는지 확인
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  zookeeper_data:
  kafka_data:
  redis_data:

    # 외부 네트워크 생성 필수: docker network create akku_proxy_net
    # 서버에서 한 번만 실행하여 akku_proxy_net 네트워크를 만들어야 nginx와 통신 가능
networks:
  proxy_net:
    external: true
    name: akku_proxy_net
