user  nginx;    # nginx가 어떤 사용자 권한으로 실행될지 설정(보안상 root가 아닌 nginx 계정으로 실행)
worker_processes  auto;     # nginx가 동시에 몇 개의 CPU 코어를 사용할지

error_log  /var/log/nginx/error.log warn;   # 에러 로그 파일 위치와 로그 레벨 설정
pid        /var/run/nginx.pid;      # nginx 프로세스 ID 저장 위치

events {
    # 한 worker 프로세스가 동시에 처리할 수 있는 연결 수
    # worker 1개당 최대 1024개의 요청 처리
    worker_connections  1024;
}

http {
    # 파일 확장자에 따라 Content-Type 자동 설정
    # 예시:
    # .json -> application/json
    # .html -> text/html   
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 로그 기록 형식 정의
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    # 실제 요청 로그 저장 위치
    access_log /var/log/nginx/access.log main;

    # 파일을 빠르게 전송하도록 최적화
    # 정적 파일 다운로드 속도 개선
    sendfile        on;

    # keep-alive 연결 유지 시간 (초)
    # 클라이언트와 연결을 계속 유지해서 속도 개선
    keepalive_timeout 65;

   # 업로드 가능한 최대 파일 크기 설정
    client_max_body_size 50M;

    # 실제 서버 설정 파일 불러오는 부분 (여기에 app.conf 포함)
    include /etc/nginx/conf.d/*.conf;
}